#!/usr/bin/env bash

set -euo pipefail

#######################
# .gitlab-ci.yml jobs #
#######################

make verify

bundle exec ./bin/create_kubernetes_rules.rb --create --validate

bundle exec rubocop

bundle exec rspec

#make test
docker run --name runbooks_make-test -v $(git rev-parse --show-toplevel):/tmp/runbooks registry.gitlab.com/gitlab-com/runbooks:latest /bin/sh -c "cd /tmp/runbooks && make test" && docker rm runbooks_make-test

#make generate
docker run --name runbooks_make-generate -v $(git rev-parse --show-toplevel):/tmp/runbooks registry.gitlab.com/gitlab-com/runbooks/runtools_build:latest "cd /tmp/runbooks && make generate && git diff --exit-code || (echo 'Please run make generate' && exit 1)" && docker rm runbooks_make-generate
