---
extends: default

ignore: |
  vendor/
  mimir-rules/
  .copier-*.yml
  *.mixin.yml

rules:
  document-start: disable
  indentation:
    indent-sequences: consistent
    spaces: 2
  line-length: disable
