{
 "title": "/Users/zoebraddock/code/runbooks/dashboards/postgresql: Database Decomposition using logical",
 "description": "Uploaded by zoebraddock at Wed 12 Mar 2025 01:56:59 UTC",
 "tags": [
  "managed",
  "/Users/zoebraddock/code/runbooks/dashboards/postgresql",
  "postgresql"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "src_cluster",
    "query": "label_values(pg_settings_server_version_num, fqdn)"
   },
   {
    "name": "dst_cluster",
    "query": "label_values(pg_settings_server_version_num, fqdn)"
   },
   {
    "name": "version",
    "query": "query_result(min by(__name__) (pg_settings_server_version_num{fqdn=~\"patroni-${src_cluster}.*\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Context",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "content": "# **$environment** **$src_cluster** **$dst_cluster**"
  },
  {
   "title": "Cluster on the left",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "content": "🏹 Source cluster: ${src_cluster}, Ubuntu 20.04"
  },
  {
   "title": "Logical replication lag (all slots in $environment)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pg_replication_slots_confirmed_flush_lsn_bytes{env=\"$environment\", slot_type=\"logical\"}) by (fqdn, slot_type, slot_name)\n"
    }
   ]
  },
  {
   "title": "Useful links",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "content": "\n- [Ansible playbooks](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/tree/master/pg-physical-to-logical)\n- [Inventory in Ansible](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/tree/master/pg-physical-to-logical/inventory)\n- [CR template](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/blob/master/.gitlab/issue_templates/decomposition.md) (individual CRs are to be located at ops.gitlab.net)\n- [Diagram illustrating the process](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/blob/master/.gitlab/issue_templates/decomposition.md#high-level-overview)\n    "
  },
  {
   "title": "Cluster on the right",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "content": "🎯 Target cluster: ${dst_cluster} "
  },
  {
   "title": "Physical lags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 🏃🏻‍♀️ Physical replication lag on source standbys, in seconds",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(pg_replication_lag{env=\"$environment\", fqdn=~\"patroni-${src_cluster}-v${version}.*\"}) by (fqdn)\n"
      }
     ]
    },
    {
     "title": "🎯 🏃🏻‍♀️ Physical replication lag on target standbys, in seconds",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(pg_replication_lag{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}) by (fqdn)\n"
      }
     ]
    },
    {
     "title": "🏹 🏃🏻‍♀️ Physical replication lag on source standbys, in bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(postgres:pg_replication_lag_bytes{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}) by (fqdn)\n"
      }
     ]
    },
    {
     "title": "🎯 🏃🏻‍♀️ Physical replication lag on target standbys, in bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(postgres:pg_replication_lag_bytes{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}) by (fqdn)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "TPS (commits)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 🥇 Source leader TPS (commits) ✅",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🎯 🥇 Target leader TPS (commits) ✅",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🏹 👥 Source standbys TPS (commits) ✅",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 👥 Target standbys TPS (commits) ✅",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "TPS rollbacks – ERROR RATES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 🥇 Source leader rollback TPS – ERRORS ❌",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "err/s" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🎯 🥇 Target leader rollback TPS – ERRORS ❌",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "err/s" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🏹 👥 Source standbys roolback TPS – ERRORS ❌",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "err/s" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 👥 Target standbys rollback TPS – ERRORS ❌",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "err/s" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Tuple stats: ins/upd/del, index fetches, seq reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 Source writes (tuple ins/upd/del)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🎯 Target writes (tuple ins/upd/del)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🏹 Source writes (tuple ins/upd/del) for Decomp Tables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\", relname=~\"(dast_pre_scan_verification_steps|dast_pre_scan_verifications|dast_profile_schedules|dast_profiles|dast_profiles_pipelines|dast_profiles_tags|dast_scanner_profiles|dast_scanner_profiles_builds|dast_site_profile_secret_variables|dast_site_profiles|dast_site_profiles_builds|dast_site_tokens|dast_site_validations|dast_sites|dependency_list_export_parts|dependency_list_exports|group_security_exclusions|project_security_exclusions|project_security_statistics|sbom_component_versions|sbom_components|sbom_occurrences|sbom_occurrences_vulnerabilities|sbom_source_packages|sbom_sources|security_findings|security_scans|vulnerabilities|vulnerability_archive_exports|vulnerability_archived_records|vulnerability_archives|vulnerability_export_parts|vulnerability_exports|vulnerability_external_issue_links|vulnerability_feedback|vulnerability_finding_evidences|vulnerability_finding_links|vulnerability_finding_signatures|vulnerability_findings_remediations|vulnerability_flags|vulnerability_historical_statistics|vulnerability_identifiers|vulnerability_issue_links|vulnerability_merge_request_links|vulnerability_namespace_historical_statistics|vulnerability_occurrence_identifiers|vulnerability_occurrences|vulnerability_reads|vulnerability_remediations|vulnerability_representation_information|vulnerability_scanners|vulnerability_severity_overrides|vulnerability_state_transitions|vulnerability_statistics|vulnerability_user_mentions)\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\", relname=~\"(dast_pre_scan_verification_steps|dast_pre_scan_verifications|dast_profile_schedules|dast_profiles|dast_profiles_pipelines|dast_profiles_tags|dast_scanner_profiles|dast_scanner_profiles_builds|dast_site_profile_secret_variables|dast_site_profiles|dast_site_profiles_builds|dast_site_tokens|dast_site_validations|dast_sites|dependency_list_export_parts|dependency_list_exports|group_security_exclusions|project_security_exclusions|project_security_statistics|sbom_component_versions|sbom_components|sbom_occurrences|sbom_occurrences_vulnerabilities|sbom_source_packages|sbom_sources|security_findings|security_scans|vulnerabilities|vulnerability_archive_exports|vulnerability_archived_records|vulnerability_archives|vulnerability_export_parts|vulnerability_exports|vulnerability_external_issue_links|vulnerability_feedback|vulnerability_finding_evidences|vulnerability_finding_links|vulnerability_finding_signatures|vulnerability_findings_remediations|vulnerability_flags|vulnerability_historical_statistics|vulnerability_identifiers|vulnerability_issue_links|vulnerability_merge_request_links|vulnerability_namespace_historical_statistics|vulnerability_occurrence_identifiers|vulnerability_occurrences|vulnerability_reads|vulnerability_remediations|vulnerability_representation_information|vulnerability_scanners|vulnerability_severity_overrides|vulnerability_state_transitions|vulnerability_statistics|vulnerability_user_mentions)\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\", relname=~\"(dast_pre_scan_verification_steps|dast_pre_scan_verifications|dast_profile_schedules|dast_profiles|dast_profiles_pipelines|dast_profiles_tags|dast_scanner_profiles|dast_scanner_profiles_builds|dast_site_profile_secret_variables|dast_site_profiles|dast_site_profiles_builds|dast_site_tokens|dast_site_validations|dast_sites|dependency_list_export_parts|dependency_list_exports|group_security_exclusions|project_security_exclusions|project_security_statistics|sbom_component_versions|sbom_components|sbom_occurrences|sbom_occurrences_vulnerabilities|sbom_source_packages|sbom_sources|security_findings|security_scans|vulnerabilities|vulnerability_archive_exports|vulnerability_archived_records|vulnerability_archives|vulnerability_export_parts|vulnerability_exports|vulnerability_external_issue_links|vulnerability_feedback|vulnerability_finding_evidences|vulnerability_finding_links|vulnerability_finding_signatures|vulnerability_findings_remediations|vulnerability_flags|vulnerability_historical_statistics|vulnerability_identifiers|vulnerability_issue_links|vulnerability_merge_request_links|vulnerability_namespace_historical_statistics|vulnerability_occurrence_identifiers|vulnerability_occurrences|vulnerability_reads|vulnerability_remediations|vulnerability_representation_information|vulnerability_scanners|vulnerability_severity_overrides|vulnerability_state_transitions|vulnerability_statistics|vulnerability_user_mentions)\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🎯 Target writes (tuple ins/upd/del) for Decomp Tables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\", relname=~\"(dast_pre_scan_verification_steps|dast_pre_scan_verifications|dast_profile_schedules|dast_profiles|dast_profiles_pipelines|dast_profiles_tags|dast_scanner_profiles|dast_scanner_profiles_builds|dast_site_profile_secret_variables|dast_site_profiles|dast_site_profiles_builds|dast_site_tokens|dast_site_validations|dast_sites|dependency_list_export_parts|dependency_list_exports|group_security_exclusions|project_security_exclusions|project_security_statistics|sbom_component_versions|sbom_components|sbom_occurrences|sbom_occurrences_vulnerabilities|sbom_source_packages|sbom_sources|security_findings|security_scans|vulnerabilities|vulnerability_archive_exports|vulnerability_archived_records|vulnerability_archives|vulnerability_export_parts|vulnerability_exports|vulnerability_external_issue_links|vulnerability_feedback|vulnerability_finding_evidences|vulnerability_finding_links|vulnerability_finding_signatures|vulnerability_findings_remediations|vulnerability_flags|vulnerability_historical_statistics|vulnerability_identifiers|vulnerability_issue_links|vulnerability_merge_request_links|vulnerability_namespace_historical_statistics|vulnerability_occurrence_identifiers|vulnerability_occurrences|vulnerability_reads|vulnerability_remediations|vulnerability_representation_information|vulnerability_scanners|vulnerability_severity_overrides|vulnerability_state_transitions|vulnerability_statistics|vulnerability_user_mentions)\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\", relname=~\"(dast_pre_scan_verification_steps|dast_pre_scan_verifications|dast_profile_schedules|dast_profiles|dast_profiles_pipelines|dast_profiles_tags|dast_scanner_profiles|dast_scanner_profiles_builds|dast_site_profile_secret_variables|dast_site_profiles|dast_site_profiles_builds|dast_site_tokens|dast_site_validations|dast_sites|dependency_list_export_parts|dependency_list_exports|group_security_exclusions|project_security_exclusions|project_security_statistics|sbom_component_versions|sbom_components|sbom_occurrences|sbom_occurrences_vulnerabilities|sbom_source_packages|sbom_sources|security_findings|security_scans|vulnerabilities|vulnerability_archive_exports|vulnerability_archived_records|vulnerability_archives|vulnerability_export_parts|vulnerability_exports|vulnerability_external_issue_links|vulnerability_feedback|vulnerability_finding_evidences|vulnerability_finding_links|vulnerability_finding_signatures|vulnerability_findings_remediations|vulnerability_flags|vulnerability_historical_statistics|vulnerability_identifiers|vulnerability_issue_links|vulnerability_merge_request_links|vulnerability_namespace_historical_statistics|vulnerability_occurrence_identifiers|vulnerability_occurrences|vulnerability_reads|vulnerability_remediations|vulnerability_representation_information|vulnerability_scanners|vulnerability_severity_overrides|vulnerability_state_transitions|vulnerability_statistics|vulnerability_user_mentions)\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\", relname=~\"(dast_pre_scan_verification_steps|dast_pre_scan_verifications|dast_profile_schedules|dast_profiles|dast_profiles_pipelines|dast_profiles_tags|dast_scanner_profiles|dast_scanner_profiles_builds|dast_site_profile_secret_variables|dast_site_profiles|dast_site_profiles_builds|dast_site_tokens|dast_site_validations|dast_sites|dependency_list_export_parts|dependency_list_exports|group_security_exclusions|project_security_exclusions|project_security_statistics|sbom_component_versions|sbom_components|sbom_occurrences|sbom_occurrences_vulnerabilities|sbom_source_packages|sbom_sources|security_findings|security_scans|vulnerabilities|vulnerability_archive_exports|vulnerability_archived_records|vulnerability_archives|vulnerability_export_parts|vulnerability_exports|vulnerability_external_issue_links|vulnerability_feedback|vulnerability_finding_evidences|vulnerability_finding_links|vulnerability_finding_signatures|vulnerability_findings_remediations|vulnerability_flags|vulnerability_historical_statistics|vulnerability_identifiers|vulnerability_issue_links|vulnerability_merge_request_links|vulnerability_namespace_historical_statistics|vulnerability_occurrence_identifiers|vulnerability_occurrences|vulnerability_reads|vulnerability_remediations|vulnerability_representation_information|vulnerability_scanners|vulnerability_severity_overrides|vulnerability_state_transitions|vulnerability_statistics|vulnerability_user_mentions)\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🏹 Source index tuple fetches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_tup_fetch{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 Target index tuple fetches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_tup_fetch{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🏹 Source seq tuple reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 Target seq tuple reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🏹 Source seq tuple reads for Decomp Tables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$environment\", fqdn=~\"(patroni-${src_cluster}-v${version}|patroni-${src_cluster}-[0-9]+).*\", relname=~\"(dast_pre_scan_verification_steps|dast_pre_scan_verifications|dast_profile_schedules|dast_profiles|dast_profiles_pipelines|dast_profiles_tags|dast_scanner_profiles|dast_scanner_profiles_builds|dast_site_profile_secret_variables|dast_site_profiles|dast_site_profiles_builds|dast_site_tokens|dast_site_validations|dast_sites|dependency_list_export_parts|dependency_list_exports|group_security_exclusions|project_security_exclusions|project_security_statistics|sbom_component_versions|sbom_components|sbom_occurrences|sbom_occurrences_vulnerabilities|sbom_source_packages|sbom_sources|security_findings|security_scans|vulnerabilities|vulnerability_archive_exports|vulnerability_archived_records|vulnerability_archives|vulnerability_export_parts|vulnerability_exports|vulnerability_external_issue_links|vulnerability_feedback|vulnerability_finding_evidences|vulnerability_finding_links|vulnerability_finding_signatures|vulnerability_findings_remediations|vulnerability_flags|vulnerability_historical_statistics|vulnerability_identifiers|vulnerability_issue_links|vulnerability_merge_request_links|vulnerability_namespace_historical_statistics|vulnerability_occurrence_identifiers|vulnerability_occurrences|vulnerability_reads|vulnerability_remediations|vulnerability_representation_information|vulnerability_scanners|vulnerability_severity_overrides|vulnerability_state_transitions|vulnerability_statistics|vulnerability_user_mentions)\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 Target seq tuple reads for Decomp Tables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$environment\", fqdn=~\"patroni-${dst_cluster}-v${version}-.*\", relname=~\"(dast_pre_scan_verification_steps|dast_pre_scan_verifications|dast_profile_schedules|dast_profiles|dast_profiles_pipelines|dast_profiles_tags|dast_scanner_profiles|dast_scanner_profiles_builds|dast_site_profile_secret_variables|dast_site_profiles|dast_site_profiles_builds|dast_site_tokens|dast_site_validations|dast_sites|dependency_list_export_parts|dependency_list_exports|group_security_exclusions|project_security_exclusions|project_security_statistics|sbom_component_versions|sbom_components|sbom_occurrences|sbom_occurrences_vulnerabilities|sbom_source_packages|sbom_sources|security_findings|security_scans|vulnerabilities|vulnerability_archive_exports|vulnerability_archived_records|vulnerability_archives|vulnerability_export_parts|vulnerability_exports|vulnerability_external_issue_links|vulnerability_feedback|vulnerability_finding_evidences|vulnerability_finding_links|vulnerability_finding_signatures|vulnerability_findings_remediations|vulnerability_flags|vulnerability_historical_statistics|vulnerability_identifiers|vulnerability_issue_links|vulnerability_merge_request_links|vulnerability_namespace_historical_statistics|vulnerability_occurrence_identifiers|vulnerability_occurrences|vulnerability_reads|vulnerability_remediations|vulnerability_representation_information|vulnerability_scanners|vulnerability_severity_overrides|vulnerability_state_transitions|vulnerability_statistics|vulnerability_user_mentions)\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    }
   ]
  }
 ]
}