// This file is autogenerated using scripts/generate-service-dashboards
// Please feel free to customize this file.
local serviceDashboard = import 'gitlab-dashboards/service_dashboard.libsonnet';

serviceDashboard.overview('redis-cluster-shared-state')
.overviewTrailer()
