{
 "title": "Application Info",
 "tags": [
  "docker",
  "registry",
  "internals"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "env",
    "query": "label_values(up{job=\"prometheus\"}, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Process CPU Time",
   "type": "graph",
   "description": "CPU time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\".*registry.*\", env=~\"$env\"}[$__interval])",
     "legendFormat": "{{ pod }} || {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "graph",
   "description": "Resident memory size",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\".*registry.*\", env=~\"$env\"}",
     "legendFormat": "{{ pod }} || {{ fqdn }} Resident Memory"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\".*registry.*\", env=~\"$env\"}",
     "legendFormat": "{{ pod }} || {{ fqdn }}"
    }
   ]
  },
  { "title": "Registry Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "The HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_requests_total{env=~\"$env\"}[1m])) by (handler, code)",
     "legendFormat": "{{ handler }}: {{ code }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests",
   "type": "graph",
   "description": "The in-flight HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_in_flight_requests{env=~\"$env\"}[1m])) by (handler, code)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Registry Action Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(registry_storage_action_seconds_sum{job=~\".*registry.*\", env=~\"$env\"}[$__interval])) by (action)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Registry Cache Requests Rate",
   "type": "graph",
   "description": "The rate of registry cache requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_storage_cache_total{env=~\"$env\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{env=\"$env\",type=\"Hit\"}[$__interval])) / sum(rate(registry_storage_cache_total{env=\"$env\",type=\"Request\"}[$__interval]))"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Manifest HTTP Request Latencies in seconds (manifest)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"manifest\", env=~\"$env\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload_chunk)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload_chunk\", env=~\"$env\"}[10m])"
    }
   ]
  },
  {
   "title": "HTTP Request Latencies in seconds (blob)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob\", env=~\"$env\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (base)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"base\", env=~\"$env\"}[10m])"
    }
   ]
  },
  {
   "title": "Tags HTTP Request Latencies in seconds (tags)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"tags\", env=~\"$env\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload\", env=~\"$env\"}[10m])"
    }
   ]
  }
 ]
}