{
 "title": "Pod Metrics",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Deployment", "query": "gitlab-registry" },
   {
    "name": "Node",
    "query": "query_result(count(count_over_time(kube_node_labels{env=\"gstg\"}[1w])) by (label_kubernetes_io_hostname))"
   },
   {
    "name": "env",
    "query": "label_values(up{job=\"prometheus\"}, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$env\", pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\", pod_name!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{env=~\"$env\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$env\", pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{env=~\"$env\", kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(kube_deployment_status_replicas{env=~\"$env\", deployment=~\".*$Deployment\"}) or vector(0)) - ((sum(kube_deployment_status_replicas_available{env=~\"$env\", deployment=~\".*$Deployment\"}) or vector(0)))) / (sum(kube_deployment_status_replicas{env=~\"$env\", deployment=~\".*$Deployment\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$env\", pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\", pod_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes{env=~\"$env\", node=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$env\", pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{env=~\"$env\", kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{env=~\"$env\", deployment=~\".*$Deployment\"})"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{env=~\"$env\", deployment=~\".*$Deployment\"})",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$env\", image!=\"\", pod_name=~\"^$Deployment.*$\", node=~\"^$Node$\"}[1m])) by (pod_name,node)",
     "legendFormat": "real: {{ node }} | {{ pod_name }} "
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{env=~\"$env\", pod=~\"^$Deployment.*$\",node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{env=~\"$env\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests_cpu_cores{env=~\"$env\"}\n  * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  label_replace(\n    namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{env=~\"$env\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n/sum(\n  kube_pod_container_resource_requests_cpu_cores{env=~\"$env\"}\n  * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits_cpu_cores{env=~\"$env\"}\n  * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  label_replace(\n    namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{env=~\"$env\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n/sum(\n  kube_pod_container_resource_limits_cpu_cores{env=~\"$env\"}\n  * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$env\", id!=\"/\",pod_name=~\"^$Deployment.*$\",node=~\"^$Node$\"}) by (pod_name,node)",
     "legendFormat": "real: {{ node }} | {{ pod_name }}"
    },
    {
     "expr": "sum ((kube_pod_container_resource_requests_memory_bytes{env=~\"$env\", pod=~\"^$Deployment.*$\",node=~\"^$Node$\"})) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    container_memory_usage_bytes{env=~\"$env\", container_name!=\"\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n  ) by (pod)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests_memory_bytes{env=~\"$env\"}\n  * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  label_replace(\n    container_memory_usage_bytes{env=~\"$env\", container_name!=\"\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n  ) by (pod)\n/sum(\n  kube_pod_container_resource_requests_memory_bytes{env=~\"$env\", }\n  * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits_memory_bytes{env=~\"$env\"}\n  * on(pod) group_left(workload) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n  label_replace(\n    container_memory_usage_bytes{env=~\"$env\", container_name!=\"\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n  ) by (pod)\n/sum(\n  kube_pod_container_resource_limits_memory_bytes{env=~\"$env\"}\n  * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{env=~\"$env\", workload=\"gitlab-registry\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{env=~\"$env\", id!=\"/\",pod_name=~\"^$Deployment.*$\",node=~\"^$Node$\"}[1m])) by (pod_name, node)",
     "legendFormat": "-> {{ node }} | {{ pod_name }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{env=~\"$env\", id!=\"/\",pod_name=~\"^$Deployment.*$\",node=~\"^$Node$\"}[1m])) by (pod_name, node)",
     "legendFormat": "<- {{ node }} | {{ pod_name }}"
    }
   ]
  }
 ]
}