// This file is autogenerated using scripts/generate_crossover_stage_group_mappings.rb.
// Please update it manually if feature categories were renamed, as:
// {
//   "old_category": "new_category",
// }
//
// Blank values will be ignored.
{
  dependency_proxy: '',
  gitlab_docs: '',
  fulfillment_infrastructure: '',
  customersdot_application: '',
  fulfillment_admin_tooling: '',
  sm_provisioning: '',
  saas_provisioning: '',
  commerce_integrations: '',
  purchase: '',
}
