// This file is autogenerated using scripts/generate-service-dashboards
// Please feel free to customize this file.
local serviceDashboard = import 'gitlab-dashboards/service_dashboard.libsonnet';

// TODO: add common graphs for postgres dashboards

serviceDashboard.overview('runway-db-example')
.overviewTrailer()
