{
 "title": "ClickHouse Cloud Services",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clickhouse_service",
    "label": "ClickHouse Service",
    "query": {
     "query": "label_values(clickhouse_service_name)"
    }
   },
   {
    "name": "clickhouse_env",
    "label": "Env",
    "query": {
     "query": "label_values(ClickHouseMetrics_Revision,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ClickHouse Nodes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_Revision{clickhouse_service_name=~\"$clickhouse_service\", env=~\"$clickhouse_env\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{env=~\"$clickhouse_env\", clickhouse_service_name=~\"$clickhouse_service\"}",
     "legendFormat": "{{env}}-{{hostname}}"
    }
   ]
  },
  {
   "title": "Connections (TCP & HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{clickhouse_service_name=~\"$clickhouse_service\", env=~\"$clickhouse_env\"}",
     "legendFormat": "tcp-{{env}}-{{hostname}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{clickhouse_service_name=~\"$clickhouse_service\", env=~\"$clickhouse_env\"}",
     "legendFormat": "http-{{env}}-{{hostname}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_Query{clickhouse_service_name=~\"$clickhouse_service\", env=~\"$clickhouse_env\"}[$__rate_interval])",
       "legendFormat": "{{env}}-{{hostname}}"
      }
     ]
    },
    {
     "title": "Failed Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_FailedQuery{clickhouse_service_name=~\"$clickhouse_service\", env=\"$clickhouse_env\"}[$__rate_interval])",
       "legendFormat": "{{env}}-{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Insert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inserted Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_InsertedRows{clickhouse_service_name=~\"$clickhouse_service\", env=~\"$clickhouse_env\"}[$__rate_interval])",
       "legendFormat": "{{env}}-{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Select",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Select Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedRows{clickhouse_service_name=~\"$clickhouse_service\", env=~\"$clickhouse_env\"}[$__rate_interval])",
       "legendFormat": "{{env}}-{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Wait Time (Read)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_DiskReadElapsedMicroseconds{clickhouse_service_name=~\"$clickhouse_service\", env=~\"$clickhouse_env\"}[$__rate_interval])",
       "legendFormat": "{{env}}-{{hostname}}"
      }
     ]
    },
    {
     "title": "Disk Wait Time (Write)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_DiskWriteElapsedMicroseconds{clickhouse_service_name=~\"$clickhouse_service\", env=~\"$clickhouse_env\"}[$__rate_interval])",
       "legendFormat": "{{env}}-{{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}