// This file is autogenerated using scripts/update_stage_groups_dashboards.rb
// Please feel free to customize this file.
local stageGroupDashboards = import './stage-group-dashboards.libsonnet';
local grafana = import 'github.com/grafana/grafonnet-lib/grafonnet/grafana.libsonnet';
local basic = import 'grafana/basic.libsonnet';
local layout = import 'grafana/layout.libsonnet';
local template = grafana.template;
local row = grafana.row;

stageGroupDashboards.dashboard('fulfillment_platform')
.stageGroupDashboardTrailer()
.addTemplate(
  template.new(
    'instance',
    '$PROMETHEUS_DS',
    'label_values(probe_success{environment="$environment", type="blackbox"}, instance)',
    current='https://customers.gitlab.com',
    refresh='load',
  )
)
.addPanel(
  row.new(title='⏱️  Stack Component Uptime'),
  gridPos={
    x: 0,
    y: 1000,
    w: 24,
    h: 8,
  }
)
.addPanels(
  layout.columnGrid([[
    basic.slaStats(
      title='CustomersDot probe result',
      query='avg(avg_over_time(probe_success{instance="$instance", environment="$environment", type="blackbox"}[$__interval]))'
    ),
    basic.slaStats(
      title='Puma uptime',
      query='1-(avg(avg_over_time(last_scrape_error{environment="$environment", type="customersdot"}[$__interval])))',
    ),
  ]], [4, 4], rowHeight=8, startRow=1001)
)
