// This file is autogenerated using scripts/update_stage_groups_dashboards.rb
// Please feel free to customize this file.
local stageGroupDashboards = import './stage-group-dashboards.libsonnet';
local platformLinks = import 'platform_links.libsonnet';

stageGroupDashboards.dashboard('package', ['api', 'sidekiq', 'web'])
.stageGroupDashboardTrailer() + {
  links+: [
    platformLinks.dynamicLinks('Container Registry Detail', 'type:registry'),
  ],
}
