{
 "title": "Hosted Runners Logging",
 "tags": [
  "hosted-runners",
  "dedicated"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info,shard)\n"
   },
   {
    "name": "plugin",
    "query": "label_values(fluentd_output_status_flush_time_count,plugin)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Hosted Runner(s) Logging Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "hosted-runners-logging Service Error Ratio",
   "type": "timeseries",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_shard_errors:ratio_5m{component=\"usage_logs\",type=\"hosted-runners-logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{component}} - {{shard}} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"usage_logs\",type=\"hosted-runners-logging\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"usage_logs\",type=\"hosted-runners-logging\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_shard_errors:ratio_5m{component=\"usage_logs\",type=\"hosted-runners-logging\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{component}} - {{shard}} error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_shard_errors:ratio_5m{component=\"usage_logs\",type=\"hosted-runners-logging\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"usage_logs\",type=\"hosted-runners-logging\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_shard_errors:ratio_1h{component=\"usage_logs\",type=\"hosted-runners-logging\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_shard_errors:ratio_5m{component=\"usage_logs\",type=\"hosted-runners-logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"usage_logs\",type=\"hosted-runners-logging\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_shard_errors:ratio_1h{component=\"usage_logs\",type=\"hosted-runners-logging\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"usage_logs\",type=\"hosted-runners-logging\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_shard_errors:ratio_30m{component=\"usage_logs\",type=\"hosted-runners-logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"usage_logs\",type=\"hosted-runners-logging\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_shard_errors:ratio_6h{component=\"usage_logs\",type=\"hosted-runners-logging\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"usage_logs\",type=\"hosted-runners-logging\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "hosted-runners-logging Service | Errors"
    }
   ]
  },
  {
   "title": "hosted-runners-logging Service RPS - Requests per Second",
   "type": "timeseries",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_shard_ops:rate_5m{component=\"usage_logs\",type=\"hosted-runners-logging\"}[$__interval])\n",
     "legendFormat": "{{component}} - {{shard}} RPS"
    },
    {
     "expr": "gitlab_component_shard_ops:rate_5m{component=\"usage_logs\",type=\"hosted-runners-logging\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{component=\"usage_logs\",type=\"hosted-runners-logging\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{component=\"usage_logs\",type=\"hosted-runners-logging\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{component=\"usage_logs\",type=\"hosted-runners-logging\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{component=\"usage_logs\",type=\"hosted-runners-logging\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  { "title": "Fluentd Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Current emit records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (shard, plugin) (\n  increase(fluentd_output_status_emit_records{shard=~\"$shard\", plugin=~\"$plugin\"}[5m])\n)\n",
     "legendFormat": "{{shard}} - {{plugin}}"
    }
   ]
  },
  {
   "title": "Current retry wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (shard, plugin) (\n  rate(fluentd_output_status_retry_wait{shard=~\"$shard\", plugin=~\"$plugin\"}[5m])\n)\n",
     "legendFormat": "{{shard}} - {{plugin}}"
    }
   ]
  },
  {
   "title": "Current write counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (shard, plugin) (\n  increase(fluentd_output_status_write_count{shard=~\"$shard\", plugin=~\"$plugin\"}[5m])\n)\n",
     "legendFormat": "{{shard}} - {{plugin}}"
    }
   ]
  },
  {
   "title": "Fluentd output error/retry rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (shard, plugin) (\n  rate(fluentd_output_status_retry_count{shard=~\"$shard\", plugin=~\"$plugin\"}[5m])\n)\n",
     "legendFormat": "{{shard}} - {{plugin}} - Retry rate"
    },
    {
     "expr": "sum by (shard, plugin) (\n    rate(fluentd_output_status_num_errors{shard=~\"$shard\", plugin=~\"$plugin\"}[5m])\n)\n",
     "legendFormat": "{{shard}} - {{plugin}} - Error rate"
    }
   ]
  },
  {
   "title": "Fluentd output status flush time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1009 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (shard, plugin) (\n  rate(fluentd_output_status_flush_time_count{shard=~\"$shard\", plugin=~\"$plugin\"}[5m])\n)\n",
     "legendFormat": "{{shard}} - {{plugin}} - Time"
    }
   ]
  },
  {
   "title": "Maximum buffer length in last 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1009 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (shard, plugin) (\n  max_over_time(fluentd_output_status_buffer_queue_length{shard=~\"$shard\", plugin=~\"$plugin\"}[5m])\n)\n",
     "legendFormat": "{{shard}} - {{plugin}} - Count"
    }
   ]
  },
  {
   "title": "Total size of queue buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1009 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (shard, plugin) (\n  fluentd_output_status_buffer_total_bytes{shard=~\"$shard\", plugin=~\"$plugin\"}\n)\n",
     "legendFormat": "{{shard}} - {{plugin}}"
    }
   ]
  },
  {
   "title": "Buffer available space ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1009 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min by(plugin, shard) (\n  fluentd_output_status_buffer_available_space_ratio{shard=~\"$shard\", plugin=~\"$plugin\"}\n)\n",
     "legendFormat": "{{shard}} - {{plugin}}"
    }
   ]
  },
  { "title": "Replication Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Operations pending replication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(aws_s3_operations_pending_replication_sum{rule_id=\"replication-rule-hosted-runner\"}[10m])\n",
     "legendFormat": "Pending operations"
    }
   ]
  },
  {
   "title": "Replication latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2001 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(aws_s3_replication_latency_maximum{rule_id=\"replication-rule-hosted-runner\"}[10m])\n",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Bytes pending replication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2001 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(aws_s3_bytes_pending_replication_maximum{rule_id=\"replication-rule-hosted-runner\"}[10m])\n",
     "legendFormat": "Bytes pending"
    }
   ]
  },
  {
   "title": "Operations failed replication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(aws_s3_operations_failed_replication_sum{rule_id=\"replication-rule-hosted-runner\"}[10m])\n",
     "legendFormat": "Failed replication"
    }
   ]
  }
 ]
}