{
 "title": "Hosted Runners SLO",
 "tags": [
  "hosted-runners",
  "slas",
  "service-levels"
 ],
 "time": { "from": "now-1M/M", "to": "now-1d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Hosted runners ci_runner_jobs availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Overall Availability",
   "type": "stat",
   "description": "Percentage of ci_runner_jobs over the dashboard's range that did not have internal errors.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum by(component) (\n  gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"} -  gitlab_service_errors:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n)[$__range:1m])\n/\nsum_over_time(\n  sum by(component) (\n    gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n  )[$__range:1m])\n"
    }
   ]
  },
  {
   "title": "Availability Budget Spent",
   "type": "stat",
   "description": "Estimated time over the dashboard's period where ci_runner_jobs failed due to internal errors",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    sum_over_time(sum by(component) (\n      gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"} -  gitlab_service_errors:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n    )[$__range:1m])\n    /\n    sum_over_time(\n      sum by(component) (\n        gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n      )[$__range:1m])\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Rolling availability",
   "type": "graph",
   "description": "Percentage of ci_runner_jobs over the dashboard's range that did not have internal errors, looking back over the dashboard's range window.",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(sum by(component) (\n  gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"} -  gitlab_service_errors:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n)[$__range:$__interval])\n/\nsum_over_time(\n  sum by(component) (\n    gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n  )[$__range:$__interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hosted runners job queuing SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Job Queuing Duration SLO",
   "type": "stat",
   "description": "Percentage of all jobs over the dashboard's range that were executed within an acceptable time. Excludes jobs that were delayed because the scaleMax threshold was hit.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(sum_over_time(\n  (\n    sum by (shard) (\n      increase(\n        (\n          sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n        )[1m:1m]\n      )\n    ) *\n    (\n      min_over_time(\n        (sum by(shard)(fleeting_provisioner_instances{type=\"hosted-runners\", state!=\"deleting\"}) < bool sum by(shard)(fleeting_provisioner_max_instances) * .9)[2m:1m]\n      )\n    )\n  )[$__range:1m]\n)\n) /\nincrease(sum(gitlab_runner_jobs_total{type=\"hosted-runners\"})[$__range:1m])\n"
    }
   ]
  },
  {
   "title": "Queuing Duration Violations Count",
   "type": "stat",
   "description": "Number of jobs over the dashboard's range that exceeded the acceptable time. Excludes jobs that were delayed because the scaleMax threshold was hit.",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(\n  (\n    sum by (shard) (\n      increase(\n        (\n          sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n        )[1m:1m]\n      )\n    ) *\n    (\n      min_over_time(\n        (sum by(shard)(fleeting_provisioner_instances{type=\"hosted-runners\", state!=\"deleting\"}) < bool sum by(shard)(fleeting_provisioner_max_instances) * .9)[2m:1m]\n      )\n    )\n  )[$__range:1m]\n))\n"
    }
   ]
  },
  {
   "title": "Job Queuing Duration SLO Over Time",
   "type": "graph",
   "description": "Percentage of all jobs looking back over the dashboard's range that were executed within an acceptable time. Excludes jobs that were delayed because the scaleMax threshold was hit.",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 -\nsum(sum_over_time(\n  (\n    sum by (shard) (\n      increase(\n        (\n          sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n        )[1m:1m]\n      )\n    ) *\n    (\n      min_over_time(\n        (sum by(shard)(fleeting_provisioner_instances{type=\"hosted-runners\", state!=\"deleting\"}) < bool sum by(shard)(fleeting_provisioner_max_instances) * .9)[2m:1m]\n      )\n    )\n  )[$__range:$__interval]\n)) /\nincrease(sum(gitlab_runner_jobs_total{type=\"hosted-runners\"})[$__range:$__interval])\n",
     "legendFormat": "Job Queuing SLO"
    }
   ]
  }
 ]
}