{
 "title": "Hosted Runners Overview",
 "tags": [
  "hosted-runners",
  "dedicated"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info,shard)\n"
   }
  ]
 },
 "panels": [
  { "title": "Hosted Runner(s) Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "hosted-runners Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_shard_apdex:ratio_5m{type=\"hosted-runners\"}[$__interval])\n",
     "legendFormat": "{{component}} - {{shard}} apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"hosted-runners\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"hosted-runners\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_shard_apdex:ratio_5m{type=\"hosted-runners\"}[$__interval])\n",
     "legendFormat": "{{component}} - {{shard}} apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_shard_apdex:ratio_5m{type=\"hosted-runners\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"hosted-runners\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_shard_apdex:ratio_1h{type=\"hosted-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_shard_apdex:ratio_5m{type=\"hosted-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"hosted-runners\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_shard_apdex:ratio_1h{type=\"hosted-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"hosted-runners\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_shard_apdex:ratio_30m{type=\"hosted-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"hosted-runners\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_shard_apdex:ratio_6h{type=\"hosted-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"hosted-runners\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "hosted-runners Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "hosted-runners Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_shard_errors:ratio_5m{type=\"hosted-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{component}} - {{shard}} error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"hosted-runners\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"hosted-runners\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_shard_errors:ratio_5m{type=\"hosted-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "{{component}} - {{shard}} error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_shard_errors:ratio_5m{type=\"hosted-runners\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"hosted-runners\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_shard_errors:ratio_1h{type=\"hosted-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_shard_errors:ratio_5m{type=\"hosted-runners\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"hosted-runners\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_shard_errors:ratio_1h{type=\"hosted-runners\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"hosted-runners\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_shard_errors:ratio_30m{type=\"hosted-runners\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"hosted-runners\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_shard_errors:ratio_6h{type=\"hosted-runners\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"hosted-runners\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "hosted-runners Service | Errors"
    }
   ]
  },
  {
   "title": "hosted-runners Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_shard_ops:rate_5m{type=\"hosted-runners\"}[$__interval])\n",
     "legendFormat": "{{component}} - {{shard}} RPS"
    },
    {
     "expr": "gitlab_component_shard_ops:rate_5m{type=\"hosted-runners\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{type=\"hosted-runners\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{type=\"hosted-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{type=\"hosted-runners\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{type=\"hosted-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{type=\"hosted-runners\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "GitLab Runner(s) Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gitlab_runner_version_info{job=\"hosted-runners-prometheus-agent\"}\n"
    }
   ]
  },
  {
   "title": "GitLab Runner(s) Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"hosted-runners-prometheus-agent\"}\n"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "content": "This is global overview of all hosted runners.\n\nFor more information check the hosted runner dashboard in the runner project.\n"
  },
  { "title": "Runner Manager Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  vector(0) and on() (\n    (sum(gitlab_component_shard_ops:rate_5m{component=\"api_requests\", shard=~\"$shard\"}) by (shard) > 0)\n  )\n  or vector(1)\n)\n",
     "legendFormat": "Runner Manager Status"
    }
   ]
  },
  {
   "title": "Total Job Executed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_jobs_total{shard=~\"$shard\"}\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Total Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_failed_jobs_total{shard=~\"$shard\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Jobs Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_jobs{shard=~\"$shard\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(floor(\n  (\n    gitlab_component_saturation:ratio{type=\"hosted-runners\", shard=~\"$shard\"}\n  )\n), 0)\n",
     "legendFormat": "Job Concurrency Status"
    }
   ]
  },
  {
   "title": "Concurrent Job Limit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_concurrent{shard=~\"$shard\"}\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Runner Manager Caught Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1002 },
   "yaxes": [
    { "format": "short", "label": "Erros" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(\n    gitlab_runner_errors_total{shard=~\"$shard\"} [$__rate_interval]\n  )\n) by (level, shard)\n",
     "legendFormat": "{{shard}}: {{level}}"
    }
   ]
  },
  {
   "title": "Failed Job errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1002 },
   "yaxes": [
    { "format": "short", "label": "Erros" }
   ],
   "targets": [
    {
     "expr": "sum by (shard, failure_reason) (\n  rate(gitlab_runner_failed_jobs_total{shard=~\"$shard\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{shard}}: {{failure_reason}}"
    }
   ]
  },
  {
   "title": "Runner saturation of concurrent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1002 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "gitlab_component_saturation:ratio{type=\"hosted-runners\", shard=~\"$shard\"}\n",
     "legendFormat": "{{ shard }} jobs running"
    },
    { "expr": "0.85", "legendFormat": "Soft SLO" },
    { "expr": "0.95", "legendFormat": "Hard SLO" }
   ]
  },
  {
   "title": "Total number of api requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1003 },
   "yaxes": [
    { "format": "short", "label": "Api requests" }
   ],
   "targets": [
    {
     "expr": "sum by(status, shard, endpoint) (\n  increase(\n    gitlab_runner_api_request_statuses_total{shard=~\"$shard\"} [$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}} : api {{endpoint}} : status {{status}}"
    }
   ]
  },
  {
   "title": "Running jobs phase",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1003 },
   "yaxes": [
    { "format": "short", "label": "Running jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (executor_stage, stage, shard) (\n  gitlab_runner_jobs{state=\"running\", shard=~\"$shard\"}\n)\n",
     "legendFormat": "{{shard}} : {{executor_stage}} : {{stage}}"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1003 },
   "content": "The Grafana Hosted Runner Manager Dashboard for dedicated environments provides a real-time view of GitLab runners' performance.\n\nIt tracks key metrics like job execution times, runner utilization, system health, and alerts for issues such as downtime\nor job failures. This dashboard helps optimize runner performance and resource management in dedicated setups, ensuring efficient CI/CD workflows.\n"
  },
  { "title": "Pending Jobs", "type": "row", "gridPos": { "h": 100, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Pending job queue duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2001 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(\n    gitlab_runner_job_queue_duration_seconds_bucket{shard=~\"$shard\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending Builds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Pending Builds" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (increase(\n  ci_pending_builds{shared_runners=\"no\"} [$__rate_interval]\n))\n",
     "legendFormat": "pending builds"
    }
   ]
  },
  {
   "title": "Acceptable job queuing duration exceeded",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (shard) (\n  increase(\n    gitlab_runner_acceptable_job_queuing_duration_exceeded_total{shard=~\"$shard\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Jobs Queuing Failure Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2002 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (shard) (\n  rate(\n    gitlab_runner_acceptable_job_queuing_duration_exceeded_total{shard=~\"$shard\"}[$__rate_interval]\n  )\n)\n/\nsum by (shard) (\n  rate(\n    gitlab_runner_jobs_total{shard=~\"$shard\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Average duration of queuing",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2002 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (shard) (\n  rate(gitlab_runner_job_queue_duration_seconds_sum{shard=~\"$shard\"}[5m])\n)\n/\nsum by (shard) (\n  gitlab_component_shard_ops:rate_5m{component=\"pending_builds\", shard=~\"$shard\"}\n)\n",
     "legendFormat": "{{shard}}"
    },
    { "expr": "300", "legendFormat": "Hard SLO" }
   ]
  },
  {
   "title": "Rate of builds queue operations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2002 },
   "yaxes": [
    { "format": "short", "label": "Rate per second" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    gitlab_ci_queue_operations_total{}[$__interval]\n  )\n) by (operation)\n",
     "legendFormat": "queuing operation {{ operation }}"
    }
   ]
  },
  { "title": "Hosted Runner Minutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Finished Job Minutes Increase",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(gitlab_runner_job_duration_seconds_sum{shard=~\"$shard\"}[$__rate_interval])\n)/60\n",
     "legendFormat": "{{shard}}"
    },
    {
     "expr": "avg (\n  increase(gitlab_runner_job_duration_seconds_sum{shard=~\"$shard\"}[$__rate_interval])\n)/60\n",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Finished Job Durations Histogram",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(gitlab_runner_job_duration_seconds_bucket{shard=~\"$shard\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Hosted Runner Fleeting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "Fleeting instances saturation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(job) (\n  fleeting_provisioner_instances{state=~\"running|deleting\", shard=~\"$shard\"}\n)\n/\nsum by(job) (\n  fleeting_provisioner_max_instances{shard=~\"$shard\"}\n)\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Taskscaler tasks saturation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(job) (\n  fleeting_taskscaler_tasks{shard=~\"$shard\", state!~\"idle|reserved\"}\n)\n/\nsum by(job) (\n  fleeting_provisioner_max_instances{shard=~\"$shard\"}\n  *\n  fleeting_taskscaler_max_tasks_per_instance{shard=~\"$shard\"}\n)\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Taskscaler max use count per instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job) (\n  fleeting_taskscaler_max_use_count_per_instance{shard=~\"$shard\"}\n)\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Fleeting instance creation timing",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4002 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_provisioner_instance_creation_time_seconds_bucket{shard=~\"$shard\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleeting instance is_running timing",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 4002 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_provisioner_instance_is_running_time_seconds_bucket{shard=~\"$shard\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleeting instance deletion timing",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 4002 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_provisioner_instance_deletion_time_seconds_bucket{shard=~\"$shard\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleeting instance life duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4002 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_provisioner_instance_life_duration_seconds_bucket{shard=~\"$shard\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Polling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 } },
  {
   "title": "Polling RPS - Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5001 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum by () (\n  gitlab_component_shard_ops:rate_5m{component=\"polling\", type=\"hosted-runners\"}\n)\n",
     "legendFormat": "overall"
    }
   ]
  },
  {
   "title": "Polling Error - Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5001 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by () (\n  gitlab_component_shard_errors:rate_5m{component=\"polling\", type=\"hosted-runners\"}\n)\n",
     "legendFormat": "overall"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5001 },
   "content": "This SLI monitors job polling operations from runners (not only hosted runners), via Workhorse's /api/v4/jobs/request route.\n\n5xx responses are considered to be errors, and could indicate postgres timeouts (after 15s) on the main query used in assigning jobs to runners.\n"
  }
 ]
}