local configMap = import 'recording-rule-config-map.libsonnet';

local outputPromYaml(groups) =
  std.manifestYamlDoc({
    groups: groups,
  });

{
  'component-error-ratios.yml':
    outputPromYaml([{
      name: 'Autogenerated Component Node Error Ratios',
      interval: '1m',
      rules: configMap.prometheus.componentErrorRatios.generateRecordingRules(),
    }]),
}
