#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Check that jsonnet-tool is installed
"${SCRIPT_DIR}/ensure-jsonnet-tool.sh"

mkdir -p "${SCRIPT_DIR}/../.gitlab/dashboards"
rm -f "${SCRIPT_DIR}"/../.gitlab/dashboards/*.yml

"${SCRIPT_DIR}/generate-service-catalog-json.sh"

jsonnet_compile() {
  local warning='# WARNING. DO NOT EDIT THIS FILE BY HAND. USE ./scripts/generate-gitlab-dashboards.sh TO GENERATE IT
# YOUR CHANGES WILL BE OVERRIDDEN'

  jsonnet-tool yaml \
    --multi "${SCRIPT_DIR}/../.gitlab/dashboards" \
    --header "${warning}" \
    -J "${SCRIPT_DIR}/../libsonnet/" \
    -J "${SCRIPT_DIR}/../metrics-catalog/" \
    -J "${SCRIPT_DIR}/../services/" \
    -J "${SCRIPT_DIR}/../vendor/" \
    -P title -P id \
    "$@"
}

jsonnet_compile "${SCRIPT_DIR}/../gitlab-dashboards/gitlab-dashboards.jsonnet"
jsonnet_compile "${SCRIPT_DIR}/../gitlab-dashboards/gitlab-triage-dashboards.jsonnet"
jsonnet_compile "${SCRIPT_DIR}/../gitlab-dashboards/gitlab-slas-dashboard.jsonnet"
