#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

REPO_DIR=$(
  cd "$(dirname "${BASH_SOURCE[0]}")/.."
  pwd
)

# Check that jsonnet-tool is installed
"${REPO_DIR}/scripts/ensure-jsonnet-tool.sh"

warning="# WARNING. DO NOT EDIT THIS FILE BY HAND. USE ${REPO_DIR}/openslos/openslos.jsonnet TO GENERATE IT
# YOUR CHANGES WILL BE OVERRIDDEN"

jsonnet-tool yaml \
  --multi "${REPO_DIR}/openslos/" \
   -J "${REPO_DIR}/metrics-catalog/" \
   -J "${REPO_DIR}/services/" \
   -J "${REPO_DIR}/vendor/" \
   -J "${REPO_DIR}/libsonnet/" \
  --header "${warning}" \
  --prefix "autogenerated-" \
   "${REPO_DIR}/openslos/openslos.jsonnet"

