#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

REPO_DIR=$(
  cd "$(dirname "${BASH_SOURCE[0]}")/.."
  pwd
)

# Convert the service catalog yaml into a JSON file in a format thats consumable by jsonnet
"${REPO_DIR}/services/generate-json.sh"

tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'generate-jsonnet-rules')
trap 'rm -rf "${tmpdir}"' EXIT

function render_multi_jsonnet() {
  local dest_dir="$1"
  local filename="$2"

  tmpoutput=$(mktemp)
  jsonnet -J "$(dirname "${filename}")" -J "${REPO_DIR}/libsonnet" -J "${REPO_DIR}/metrics-catalog" -J "${REPO_DIR}/services" -o "${tmpoutput}" "${filename}"

  # Lazily create directories
  # idea taken from https://github.com/google/jsonnet/issues/195#issuecomment-221700523
  for p in $(jq -r keys[] <"$tmpoutput"); do mkdir -p "$tmpdir/$(dirname "$p")"; done
  jsonnet --string -m "${tmpdir}" "$tmpoutput" >/dev/null

  warning="# WARNING. DO NOT EDIT THIS FILE BY HAND. USE ${filename} TO GENERATE IT
# YOUR CHANGES WILL BE OVERRIDDEN"

  for i in $(jq -r keys[] <"$tmpoutput"); do
    local b
    local dir
    b=$(basename "${i}")
    dir=$(dirname "${i}")

    mkdir -p "${dest_dir}/${dir}"

    (
      echo "$warning"
      "${REPO_DIR}/scripts/fix-prom-rules.rb" "${tmpdir}/${i}"
    ) >"${dest_dir}/${dir}/autogenerated-${b}"

    rm -f "${i}"
    echo "${dest_dir}/${dir}/autogenerated-${b}"
  done

  rm -f "$tmpoutput"
}

if [[ $# == 0 ]]; then
  cd "${REPO_DIR}"
  for file in ./rules-jsonnet/*.jsonnet; do
    render_multi_jsonnet "${REPO_DIR}/rules" "${file}"
  done
  for file in ./thanos-rules-jsonnet/*.jsonnet; do
    render_multi_jsonnet "${REPO_DIR}/thanos-rules" "${file}"
  done
else
  for file in "$@"; do
    source_dir=$(dirname "${file}")
    render_multi_jsonnet "${source_dir%-jsonnet}" "${file}"
  done
fi
