#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

BAD_URLS=$(find "${ROOT_DIR}" -type f -name '*.md' -print0 | xargs -0 grep -Eo 'log.gitlab.net/app/kibana\S*_g=\S+_a=\S+')

if [[ -n "${BAD_URLS}" ]]; then
  echo "Please convert your Kibana URLS to shortlinks using the Share | Shortlink menu in Kibana"
  echo "The following incorrect URLs were detected:"
  echo "${BAD_URLS}"
  exit 1
fi
