#!/usr/bin/env ruby
# frozen_string_literal: true
require 'yaml'
require 'pathname'

dir = Pathname.new(File.join(File.dirname(__FILE__), '..')).realpath
rule_files = %w[rules thanos-rules].flat_map { |rule_dir| Dir.glob(File.join(dir, rule_dir, '*.yml')) }

duplicates = {}

rule_files.each do |file|
  rule_definitions = YAML.load_file(file)
  rule_names = rule_definitions['groups'].map { |definition| definition['name'] }

  duplicate_names = rule_names.find_all { |name| rule_names.count(name) > 1 }.uniq
  duplicates[file] = duplicate_names if duplicate_names.any?
end

msg = duplicates.map do |filename, duplicate_groups|
  "#{filename} contains duplicate definitions for #{duplicate_groups.inspect}"
end.join("\n")

warn msg

if duplicates.any?
  exit 1
else
  exit 0
end
