// This file is autogenerated using scripts/generate-service-dashboards
// Please feel free to customize this file.
local platformLinks = import 'gitlab-dashboards/platform_links.libsonnet';
local serviceDashboard = import 'gitlab-dashboards/service_dashboard.libsonnet';

// DEPRECATION WARNING: `code_suggestions` service will be removed in https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/issues/251
// Use `ai-gateway` service: https://gitlab.com/gitlab-com/runbooks/-/blob/master/metrics-catalog/services/ai-gateway.jsonnet

serviceDashboard.overview('code_suggestions')
.overviewTrailer() + {
  links+: [
    platformLinks.dynamicLinks('AI Gateway Dashboards', 'type:ai-gateway'),
  ],
}
