{
 "title": "[postgres.ai][02] Postgres aggregated query performance analysis",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(node_exporter_build_info,type)"
    }
   },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(node_exporter_build_info{tier=\"db\", type=\"$type\", environment=\"$environment\"},fqdn)"
    }
   },
   {
    "name": "topn",
    "label": "TopN",
    "query": "1,10,20,30,40,50,100,200,300,400,500"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_replication_is_replica{env=\"$environment\",fqdn=\"$fqdn\"}",
     "legendFormat": "role"
    }
   ]
  },
  {
   "title": "pg_stat_statements and pg_stat_kcache views",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Statistics (pg_stat_statements)  from ${__from:date:YYYY-MM-DD HH:mm:ss}   to ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(\n  delta(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__range])\n) by (datname,queryid))  / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n  increase(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\"}[$__range])\n) by () * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Statistics (pg_stat_kcache)  from ${__from:date:YYYY-MM-DD HH:mm:ss}   to ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_kcache_exec_system_time{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_kcache_exec_user_time{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (datname, queryid) (delta(pg_stat_kcache_exec_total_time{fqdn=\"$fqdn\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "pg_stat_statements by queryid graphs ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Top $topn statements by calls (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($topn, irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by total time (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($topn, irate(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by time per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($topn,(irate(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by rows (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by rows per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($topn,(irate(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__rate_interval]))/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by block_read_seconds (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by block_read_seconds per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($topn,(irate(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by block_write_seconds (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by block_write_seconds per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($topn,(irate(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "TODO | Top $topn statements by shared_blks_hit (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TODO | Top $topn statements by shared_blks_hit per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TODO | Top $topn statements by shared_blks_read (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TODO | Top $topn statements by shared_blks_read per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TODO | Top $topn statements by shared_blks_written (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TODO | Top $topn statements by shared_blks_written per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TODO | Top $topn statements by shared_blks_dirtied (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TODO | Top $topn statements by shared_blks_dirtied by call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top $topn statements by WAL bytes (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by WAL bytes per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\"}[$__rate_interval])/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by WAL fpi (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by WAL fpi per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\"}[$__rate_interval])/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by temp_bytes_read (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by temp_bytes_read per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\"}[$__rate_interval])/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by temp_bytes_written (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top $topn statements by temp_bytes_written per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($topn,irate(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\"}[$__rate_interval])/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "pg_stat_kcache by queryid graphs ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topn statements by CPU total time (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($topn, irate(pg_stat_kcache_exec_total_time{fqdn=\"$fqdn\"}[$__rate_interval]))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "Top $topn statements by CPU total time per call (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($topn, irate(pg_stat_kcache_exec_total_time{fqdn=\"$fqdn\"}[$__rate_interval])/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "Top $topn statements by CPU user time (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($topn, irate(pg_stat_kcache_exec_user_time{fqdn=\"$fqdn\"}[$__rate_interval]))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "Top $topn statements by CPU user time per call (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($topn, irate(pg_stat_kcache_exec_user_time{fqdn=\"$fqdn\"}[$__rate_interval])/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "Top $topn statements by CPU system time (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($topn, irate(pg_stat_kcache_exec_system_time{fqdn=\"$fqdn\"}[$__rate_interval]))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "Top $topn statements by CPU system time (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($topn, irate(pg_stat_kcache_exec_system_time{fqdn=\"$fqdn\"}[$__rate_interval])/(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval])))",
       "legendFormat": "{{queryid}}"
      }
     ]
    },
    {
     "title": "TODO | Top $topn statements by exec_writes_blks + plan_writes_blks (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "s" } }
    },
    {
     "title": "TODO | Top $topn statements by exec_reads_blks + plan_reads_blks per call (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "s" } }
    },
    {
     "title": "TODO | Top $topn statements by number of context switches (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "s" } }
    },
    {
     "title": "TODO | Top $topn statements by number of context switches per call (pg_stat_kcache)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "s" } }
    }
   ]
  },
  { "title": "Wait events (pg_wait_sampling)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Top $topn queries by wait events ",
   "type": "timeseries",
   "description": "based on pg_wait_sampling representation of wait events",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "topk($topn, (sum by (wait_type, wait_event, queryid) (irate(pg_wait_sampling_count{fqdn=\"$fqdn\", wait_type!~\"\", wait_type!~\"Activity\"}[$__rate_interval])))/100)",
     "legendFormat": "{{wait_type}} - {{wait_event}} - {{queryid}}"
    },
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{fqdn=\"$fqdn\",mode=\"idle\"})",
     "legendFormat": "CPU count"
    }
   ]
  }
 ]
}