{
 "title": "[NEW][postgres.ai][03] Postgres single query performance analysis",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(node_exporter_build_info,type)"
    }
   },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(node_exporter_build_info{tier=\"db\", type=\"$type\", environment=\"$environment\"},fqdn)"
    }
   },
   { "name": "Filters" },
   { "name": "queryid", "label": "queryid", "query": "7696253069353873242" }
  ]
 },
 "panels": [
  { "title": "Query $queryid text", "type": "text", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 }, "options": { "content": "query sql text to be here " } },
  {
   "title": "pg_stat_statements by queryid graphs ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "queryid:$queryid calls (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid wait events ",
   "type": "timeseries",
   "description": "based on pg_wait_sampling representation of wait events",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(sum by (wait_type, wait_event, queryid) (irate(pg_wait_sampling_count{fqdn=\"$fqdn\", queryid=\"$queryid\", wait_type!=\"\"}[$__rate_interval])))/100",
     "legendFormat": "{{wait_type}} - {{wait_event}} "
    }
   ]
  },
  {
   "title": "queryid:$queryid total time (pg_stat_statements) s/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sec/sec" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_seconds_total{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid time per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_seconds_total{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid rows (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_rows{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid rows per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_rows{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid block_read_seconds (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid block_read_seconds per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid block_write_seconds (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid block_write_seconds per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid WAL bytes (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid WAL bytes per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid WAL fpi (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid WAL fpi per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid temp_bytes_read (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid temp_bytes_read per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid temp_bytes_written (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid temp_bytes_written per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid CPU total time (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_kcache_exec_total_time{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid CPU total time per call (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_kcache_exec_total_time{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid CPU user time (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_kcache_exec_user_time{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "queryid:$queryid CPU system time (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(pg_stat_kcache_exec_system_time{fqdn=\"$fqdn\",queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  }
 ]
}