{
 "title": "[postgres.ai][01] Postgres node performance overview (high-level)",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(node_exporter_build_info,type)"
    }
   },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(node_exporter_build_info{tier=\"db\", type=\"$type\", environment=\"$environment\"},fqdn)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_replication_is_replica{env=\"$environment\",fqdn=\"$fqdn\"}",
     "legendFormat": "role"
    }
   ]
  },
  { "title": "ASH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Active session history (ASH)",
   "type": "timeseries",
   "description": "Graph based on pg_wait_sampling_profile view of https://github.com/postgrespro/pg_wait_sampling extension.\n\nOn vertical Axis is number of backends with specific wait event type  \n\n- Client and Activity events are not shown by default, but can be done visible by clicking on them in the legend list.\n- CPU or Uncategorised wait event means backend either is being executed on CPU or waiting for CPU or some other wait that is not known yet",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sessions" } },
   "targets": [
    {
     "expr": "(sum by (wait_type) (irate(pg_wait_sampling_count{fqdn=\"$fqdn\"}[$__rate_interval])))/100",
     "legendFormat": "{{wait_type}}"
    },
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{fqdn=\"$fqdn\",mode=\"idle\"})",
     "legendFormat": "CPU count"
    }
   ]
  },
  {
   "title": "Host stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage (% of all CPUs)",
     "type": "timeseries",
     "description": "Percentage of all CPU cores/hyperthreads",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (mode) (\n  irate(node_cpu_seconds_total{env=\"$environment\",fqdn=\"$fqdn\",mode!=\"idle\"}[$__rate_interval])\n)",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "avg by (mode) (\n  irate(node_cpu_seconds_total{env=\"$environment\",fqdn=\"$fqdn\",mode=\"idle\"}[$__rate_interval])\n)",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Load Average per CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_over_time(node_load1{env=\"$environment\",fqdn=\"$fqdn\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "LA 1 min",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg_over_time(node_load5{env=\"$environment\",fqdn=\"$fqdn\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "LA 5 min",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg_over_time(node_load15{env=\"$environment\",fqdn=\"$fqdn\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "LA 15 min",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "count without(cpu, mode) (node_cpu_seconds_total{fqdn=\"$fqdn\",mode=\"idle\"})",
       "legendFormat": "CPU count "
      }
     ]
    },
    {
     "title": "Disk IO Utilization (second per second)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{env=\"$environment\", fqdn=\"$fqdn\"}[$__rate_interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{device}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(node_context_switches_total{env=\"$environment\",fqdn=\"$fqdn\"}[$__rate_interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Context switches",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Read Latency - Mean Duration per Read Op",
     "type": "timeseries",
     "description": "This measures the mean duration for each read operation (including time spent in the I/O queue, not just time from Dispatch to Compete).\n\nGood latency should be a few milliseconds; if the graph's scale is in seconds, you have a problem!\n\nHigh read latency and deep I/O queues often occur together.  They can be caused by either increased service time from the block device (slower physical I/O) or increased demand (request arrival rate).  Note that writes can sometimes stall reads.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{env=\"$environment\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{env=\"$environment\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__rate_interval]) > 0",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{device}} read latency",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Write Latency - Mean Duration per Read Op",
     "type": "timeseries",
     "description": "This measures the mean duration for each read operation (including time spent in the I/O queue, not just time from Dispatch to Compete).\n\nGood latency should be a few milliseconds; if the graph's scale is in seconds, you have a problem!\n\nHigh read latency and deep I/O queues often occur together.  They can be caused by either increased service time from the block device (slower physical I/O) or increased demand (request arrival rate).  Note that writes can sometimes stall reads.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_write_time_seconds_total{env=\"$environment\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{env=\"$environment\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__rate_interval]) > 0",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{device}} write latency",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Read Throughput (operations/sec)",
     "type": "timeseries",
     "description": "This measures the mean count of read operations per wall-clock second from each mounted block device.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{env=\"$environment\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__rate_interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{device}} read rate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Write Throughput (operations/sec)",
     "type": "timeseries",
     "description": "This measures the mean count of write operations per wall-clock second from each mounted block device.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed_total{env=\"$environment\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__rate_interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{device}} write rate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Postgres stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Backends by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{env=\"$environment\", fqdn=\"$fqdn\"}) > 0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "pg_settings_max_connections{fqdn=\"$fqdn\"}",
     "legendFormat": "max_connections"
    }
   ]
  },
  {
   "title": "Non-idle Backends by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{env=\"$environment\", fqdn=\"$fqdn\", state !=\"idle\"}) > 0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{fqdn=\"$fqdn\",mode=\"idle\"})",
     "legendFormat": "CPU count"
    }
   ]
  },
  {
   "title": "Calls (by pg_stat_statements) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by () (irate(pg_stat_statements_calls{env=\"$environment\", fqdn=\"$fqdn\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "calls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors from Postgres logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(postgresql_errors_total{env=\"$environment\",fqdn=\"$fqdn\"}[$__rate_interval]) * 60) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by () (irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=\"$fqdn\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by () (irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Commit ratio ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by () (irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=\"$fqdn\"}[$__rate_interval]))/(sum by () (irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=\"$fqdn\"}[$__rate_interval]))+sum by () (irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=\"$fqdn\"}[$__rate_interval])))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Statements total time (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "sec/sec" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "statements total time"
    }
   ]
  },
  {
   "title": "Statements time per call  (pg_stat_statements) aka latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Statements CPU total time (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by () (irate(pg_stat_kcache_exec_total_time{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Statements CPU total time per call (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by () (irate(pg_stat_kcache_exec_total_time{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Total rows  (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows per call  (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "blk_read_time vs blk_write_time (s/s) (pg_stat_statements) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "sec/sec" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum(irate(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "blk_write_time"
    }
   ]
  },
  {
   "title": "blk_read_time vs blk_write_time (s/s) per call (pg_stat_statements) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "sec/sec" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_block_read_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum(irate(pg_stat_statements_block_write_seconds_total{fqdn=\"$fqdn\"}[$__rate_interval])/irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "blk_writes_time"
    }
   ]
  },
  {
   "title": "shared_blks_hit (bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_hit_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "shared_blks_hit (bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_hit_total{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "shared_blks_hit (bytes) per call"
    }
   ]
  },
  {
   "title": "shared_blks_read (bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_read_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "shared_blks_read"
    }
   ]
  },
  {
   "title": "shared_blks_read (bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_read_total{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "shared_blks_written (bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_written_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "shared_blks_written"
    }
   ]
  },
  {
   "title": "shared_blks_written (bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_written_total{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "shared_blks_dirtied (bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_dirtied_total{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "shared_blks_dirtied"
    }
   ]
  },
  {
   "title": "shared_blks_dirtied (bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_dirtied_total{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "shared_blks_read_ratio (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_shared_bytes_hit_total{fqdn=\"$fqdn\"}[$__rate_interval])) / (sum(irate(pg_stat_statements_shared_bytes_hit_total{fqdn=\"$fqdn\"}[$__rate_interval])) + sum(irate(pg_stat_statements_shared_bytes_read_total{fqdn=\"$fqdn\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "user_time vs system_time (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "sec/sec" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_kcache_exec_user_time{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "user time"
    },
    {
     "expr": "sum(irate(pg_stat_kcache_exec_system_time{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "system time"
    }
   ]
  },
  {
   "title": "user_time vs system_time per call (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_kcache_exec_user_time{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "user time"
    },
    {
     "expr": "sum(irate(pg_stat_kcache_exec_system_time{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "system time"
    }
   ]
  },
  {
   "title": "TODO | physical disk reads vs writes (bytes) (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "Bps" } }
  },
  {
   "title": "TODO | physical disk reads vs writes (bytes) per call (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "Bps" } }
  },
  {
   "title": "TODO | Number of context switches (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "Bps" } }
  },
  {
   "title": "TODO | Number of context switches per call (pg_stat_kcache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "Bps" } }
  },
  {
   "title": "WAL bytes (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL bytes per call  (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_wal_bytes{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL fpi (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL fpi per call  (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_statements_wal_fpi{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "temp_bytes_read vs temp_bytes_written (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate (pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "temp_bytes_read"
    },
    {
     "expr": "sum(irate(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "temp_bytes_written"
    }
   ]
  },
  {
   "title": "temp_bytes_read vs temp_bytes_written per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_temp_bytes_read{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "temp_bytes_read"
    },
    {
     "expr": "sum(rate(pg_stat_statements_temp_bytes_written{fqdn=\"$fqdn\"}[$__rate_interval]))/sum(rate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__rate_interval]))",
     "legendFormat": "temp_bytes_written"
    }
   ]
  },
  {
   "title": "Locks by mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_locks_count{env=\"$environment\", fqdn=\"$fqdn\"}[$__rate_interval]) * 60) by (mode) > 0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest non-idle transaction age, > 1 min  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_long_running_transactions_age_in_seconds{fqdn=\"$fqdn\"}",
     "legendFormat": "longest transaction"
    }
   ]
  },
  {
   "title": "Age of the oldest transaction ID that has not been frozen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_database_wraparound_age_datfrozenxid{fqdn=\"$fqdn\", datname!~\"template1|postgres\"}",
     "legendFormat": "age"
    }
   ]
  },
  {
   "title": "Age of the oldest multi-transaction ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_database_wraparound_age_datminmxid{fqdn=\"$fqdn\", datname!~\"template1|postgres\"}",
     "legendFormat": "age"
    }
   ]
  },
  { "title": "TODO | database size", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 }, "fieldConfig": { "defaults": { "unit": "short" } } },
  {
   "title": "No. of pending WAL files to be archived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_archiver_pending_wal_count{fqdn=\"$fqdn\", datname!~\"template1|postgres\"}",
     "legendFormat": "age"
    }
   ]
  },
  {
   "title": "Number of queries stuck in idle in transaction state (>10min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stuck_idle_in_transaction_queries{fqdn=\"$fqdn\"}",
     "legendFormat": "number of queries"
    }
   ]
  },
  {
   "title": "Postgres components stats (archiver, autovacuum, replication, checkpointer) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 },
   "collapsed": true,
   "panels": [
    {
     "title": "TODO |  checkpointer stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 570 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "TODO |  autovacuum stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 570 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "TODO | Replication Lag size by phase",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 578 },
     "fieldConfig": { "defaults": { "unit": "none" } }
    },
    { "title": "Replication Lag time", "type": "timeseries", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 578 }, "fieldConfig": { "defaults": { "unit": "bytes" } } },
    {
     "title": "Replication Lag Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 585 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(pg_stat_replication_pg_wal_lsn_diff{environment=\"$environment\", fqdn=\"$fqdn\"}) by (application_name, slot_name)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{slot_name}} - {{application_name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "title": "Archiver stats", "type": "timeseries", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 585 }, "fieldConfig": { "defaults": { "unit": "bytes" } } }
   ]
  }
 ]
}